
--Creacion de tablas
CREATE TABLE Estado_Ejemplar (
    ID_Estado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Estado VARCHAR2(50) NOT NULL
);

CREATE TABLE Estado_Multa (
    ID_Estado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Estado VARCHAR2(20) DEFAULT 'Pendiente' NOT NULL
);

CREATE TABLE Estado_Pedido (
    ID_Estado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Estado VARCHAR2(20) DEFAULT 'Pendiente' NOT NULL
);

CREATE TABLE Usuario (
    ID_Usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Direccion VARCHAR2(200),
    Telefono VARCHAR2(20),
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Fecha_Registro DATE NOT NULL
);

CREATE TABLE Categoria (
    ID_Categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Categoria VARCHAR2(50) NOT NULL
);

CREATE TABLE Editorial (
    ID_Editorial NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE Sucursal (
    ID_Sucursal NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre_Sucursal VARCHAR2(100) NOT NULL,
    Direccion VARCHAR2(200),
    Telefono VARCHAR2(20)
);

CREATE TABLE Libro (
    ID_Libro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Titulo VARCHAR2(200) NOT NULL,
    ID_Categoria NUMBER NOT NULL,
    ID_Editorial NUMBER NOT NULL,
    FOREIGN KEY (ID_Categoria) REFERENCES Categoria(ID_Categoria),
    FOREIGN KEY (ID_Editorial) REFERENCES Editorial(ID_Editorial)
);

CREATE TABLE Ejemplar (
    ID_Ejemplar NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_Libro NUMBER NOT NULL,
    Estado_ID NUMBER NOT NULL,
    ID_Sucursal NUMBER NOT NULL,
    FOREIGN KEY (ID_Libro) REFERENCES Libro(ID_Libro),
    FOREIGN KEY (Estado_ID) REFERENCES Estado_Ejemplar(ID_Estado),
    FOREIGN KEY (ID_Sucursal) REFERENCES Sucursal(ID_Sucursal)
);

CREATE TABLE Bibliotecario (
    ID_Bibliotecario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Telefono VARCHAR2(20)
);

CREATE TABLE Prestamo (
    ID_Prestamo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_Usuario NUMBER NOT NULL,
    ID_Ejemplar NUMBER NOT NULL,
    ID_Bibliotecario NUMBER NOT NULL,
    Fecha_Alquiler DATE NOT NULL,
    Fecha_Devolucion DATE NOT NULL,
    Devuelto CHAR(1) DEFAULT 'N' CHECK (Devuelto IN ('Y', 'N')),
    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario),
    FOREIGN KEY (ID_Ejemplar) REFERENCES Ejemplar(ID_Ejemplar),
    FOREIGN KEY (ID_Bibliotecario) REFERENCES Bibliotecario(ID_Bibliotecario)
);

CREATE TABLE Historial_Prestamos (
    ID_Historial NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_Prestamo NUMBER NOT NULL,
    Estado VARCHAR2(50) NOT NULL,
    Fecha_Cambio DATE DEFAULT SYSDATE NOT NULL,
    FOREIGN KEY (ID_Prestamo) REFERENCES Prestamo(ID_Prestamo)
);

CREATE TABLE Multa (
    ID_Multa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_Usuario NUMBER NOT NULL,
    ID_Prestamo NUMBER NOT NULL,
    Monto NUMBER(10,2) NOT NULL,
    Estado_ID NUMBER DEFAULT 1,
    Fecha_Pago DATE,
    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario),
    FOREIGN KEY (ID_Prestamo) REFERENCES Prestamo(ID_Prestamo),
    FOREIGN KEY (Estado_ID) REFERENCES Estado_Multa(ID_Estado)
);

CREATE TABLE Pedido (
    ID_Pedido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_Usuario NUMBER NOT NULL,
    Fecha_Pedido DATE NOT NULL,
    Total NUMBER(10,2) NOT NULL,
    Estado_ID NUMBER DEFAULT 1,
    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario),
    FOREIGN KEY (Estado_ID) REFERENCES Estado_Pedido(ID_Estado)
);

CREATE TABLE Autor (
    ID_Autor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL
);


CREATE TABLE Libro_Autor (
    ID_Libro NUMBER NOT NULL,
    ID_Autor NUMBER NOT NULL,
    PRIMARY KEY (ID_Libro, ID_Autor),
    FOREIGN KEY (ID_Libro) REFERENCES Libro(ID_Libro),
    FOREIGN KEY (ID_Autor) REFERENCES Autor(ID_Autor)
);

CREATE TABLE Pago (
    ID_Pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_Pedido NUMBER NOT NULL,
    Monto NUMBER(10,2) NOT NULL,
    Fecha_Pago DATE NOT NULL,
    Metodo_Pago VARCHAR2(50) NOT NULL CHECK (Metodo_Pago IN ('Tarjeta', 'Efectivo', 'Transferencia')),
    Estado_Pago VARCHAR2(20) DEFAULT 'Pendiente' CHECK (Estado_Pago IN ('Pendiente', 'Completado', 'Rechazado')),
    FOREIGN KEY (ID_Pedido) REFERENCES Pedido(ID_Pedido)
);

--creacion estado para el ejemplar, la mula y el pedido
INSERT INTO Estado_Ejemplar (Estado) VALUES ('Disponible');
INSERT INTO Estado_Ejemplar (Estado) VALUES ('Prestado');
INSERT INTO Estado_Multa (Estado) VALUES ('Pendiente');
INSERT INTO Estado_Multa (Estado) VALUES ('Pagada');
INSERT INTO Estado_Pedido (Estado) VALUES ('Pendiente');
INSERT INTO Estado_Pedido (Estado) VALUES ('Completado');

--creacion de los usarios
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Carlos Daniel Vargas', 'Calle 26 #13-30, sogamoso', '3105678923', 'carlos.vargas@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('María Fernanda Gómez', 'Carrera 7 #45-23, Bogotá', '3159876543', 'maria.gomez@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Carlos Andrés Rodríguez', 'Avenida 68 #22-10, Medellín', '3012223344', 'carlos.rodriguez@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Ana Sofía Martínez', 'Calle 50 #20-15, Cali', '3124445566', 'ana.martinez@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Juan De La Hoz', 'Carrera 15 #100-80, Barranquilla', '3207778899', 'juan.Hoz@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Laura Cristina Fernández', 'Avenida 30 #12-45, Cartagena', '3135556677', 'laura.fernandez@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('David Alejandro López', 'Calle 80 #45-60, Bucaramanga', '3166667788', 'david.lopez@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Sofía Valentina Ramírez', 'Carrera 5 #10-20, Manizales', '3172223344', 'sofia.ramirez@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Miguel Ángel Torres', 'Calle 33 #55-70, Pereira', '3229998877', 'miguel.torres@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Lucía Alejandra Herrera', 'Avenida 68 #30-22, Cúcuta', '3243332211', 'lucia.herrera@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Felipe Andrés Castro', 'Carrera 12 #34-56, Neiva', '3186547890', 'felipe.castro@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Camila Estefanía Rojas', 'Calle 20 #10-50, Ibagué', '3117894561', 'camila.rojas@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Santiago José Pardo', 'Avenida 14 #25-90, Pasto', '3221112233', 'santiago.pardo@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Valentina Marcela Ospina', 'Carrera 8 #22-33, Villavicencio', '3197778899', 'valentina.ospina@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Julián Alberto Mendoza', 'Calle 45 #60-12, Santa Marta', '3143334455', 'julian.mendoza@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Andrea Carolina Gutiérrez', 'Avenida 9 #40-50, Armenia', '3158889990', 'andrea.gutierrez@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Carlos Eduardo Mejía', 'Carrera 11 #17-45, Popayán', '3125556677', 'carlos.mejia@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Daniel Esteban Quintero', 'Calle 30 #12-90, Montería', '3106667788', 'daniel.quintero@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Isabella Natalia Vargas', 'Avenida 25 #8-30, Tunja', '3171112233', 'isabella.vargas@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Sebastián Ricardo Castaño', 'Carrera 14 #27-55, Leticia', '3242223344', 'sebastian.castano@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Mariana Juliana Acosta', 'Calle 50 #30-45, Sincelejo', '3203335566', 'mariana.acosta@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Luis Fernando Silva', 'Avenida 7 #13-70, Yopal', '3224446677', 'luis.silva@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Natalia Andrea Suárez', 'Carrera 21 #18-99, Florencia', '3115557788', 'natalia.suarez@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Juan Sebastián Ramírez', 'Calle 12 #55-78, Riohacha', '3166668899', 'juan.ramirez@utadeo.edu.co', SYSDATE);
INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro) 
VALUES ('Carolina Patricia Montoya', 'Avenida 19 #30-12, Quibdó', '3247778899', 'carolina.montoya@utadeo.edu.co', SYSDATE);

--creacion de las categorias (generos)

INSERT INTO Categoria (Nombre_Categoria) VALUES ('Ciencia');
INSERT INTO Categoria (Nombre_Categoria) VALUES ('Literatura');
INSERT INTO Categoria (Nombre_Categoria) VALUES ('Historia');
INSERT INTO Categoria (Nombre_Categoria) VALUES ('Tecnología');
INSERT INTO Categoria (Nombre_Categoria) VALUES ('Fantasía');
INSERT INTO Categoria (Nombre_Categoria) VALUES ('Ciencia Ficción');
INSERT INTO Categoria (Nombre_Categoria) VALUES ('Terror');
INSERT INTO Categoria (Nombre_Categoria) VALUES ('Arte');
INSERT INTO Categoria (Nombre_Categoria) VALUES ('Música');
INSERT INTO Categoria (Nombre_Categoria) VALUES ('Deportes');
INSERT INTO Categoria (Nombre_Categoria) VALUES ('Viajes');
INSERT INTO Categoria (Nombre_Categoria) VALUES ('Educación');

--creacion de ediotriales

INSERT INTO Editorial (Nombre) VALUES ('Allen');
INSERT INTO Editorial (Nombre) VALUES ('Minotauro');
INSERT INTO Editorial (Nombre) VALUES ('Penguin Books');
INSERT INTO Editorial (Nombre) VALUES ('Bloomsbury Publishing');
INSERT INTO Editorial (Nombre) VALUES ('Penguin Classics');
INSERT INTO Editorial (Nombre) VALUES ('Little, Brown and Company');
INSERT INTO Editorial (Nombre) VALUES ('Eher Verlag');
INSERT INTO Editorial (Nombre) VALUES ('Bantam Books');
INSERT INTO Editorial (Nombre) VALUES ('HarperCollins');
INSERT INTO Editorial (Nombre) VALUES ('Scholastic');
INSERT INTO Editorial (Nombre) VALUES ('Cambridge University Press');
INSERT INTO Editorial (Nombre) VALUES ('Alfaguara');
INSERT INTO Editorial (Nombre) VALUES ('Taschen'); 
INSERT INTO Editorial (Nombre) VALUES ('Hal Leonard Corporation'); 
INSERT INTO Editorial (Nombre) VALUES ('Editorial Deportiva de España'); 
INSERT INTO Editorial (Nombre) VALUES ('Lonely Planet'); 
INSERT INTO Editorial (Nombre) VALUES ('McGraw-Hill Education'); 

--creacion de sucursales

INSERT INTO Sucursal (Nombre_Sucursal, Direccion, Telefono) 
VALUES ('Sucursal Bogotá', 'Carrera 7 #32-16, Bogotá', '6012345678');
INSERT INTO Sucursal (Nombre_Sucursal, Direccion, Telefono) 
VALUES ('Sucursal Sogamoso', 'Calle 11 #20-30, Sogamoso', '6087654321');

--creacion de autores que hagan parte de las editoriales

INSERT INTO Autor (Nombre) VALUES ('J.K. Rowling');
INSERT INTO Autor (Nombre) VALUES ('George Orwell');
INSERT INTO Autor (Nombre) VALUES ('Stephen King');
INSERT INTO Autor (Nombre) VALUES ('Edgar Allan Poe');
INSERT INTO Autor (Nombre) VALUES ('Isaac Asimov');
INSERT INTO Autor (Nombre) VALUES ('J.R.R. Tolkien');
INSERT INTO Autor (Nombre) VALUES ('Suzanne Collins');
INSERT INTO Autor (Nombre) VALUES ('Noam Chomsky');
INSERT INTO Autor (Nombre) VALUES ('Gabriel García Márquez');
INSERT INTO Autor (Nombre) VALUES ('H.P. Lovecraft');
INSERT INTO Autor (Nombre) VALUES ('Philip K. Dick');
INSERT INTO Autor (Nombre) VALUES ('Brandon Sanderson');
INSERT INTO Autor (Nombre) VALUES ('Frida Kahlo'); 
INSERT INTO Autor (Nombre) VALUES ('Andrew Lloyd Webber'); 
INSERT INTO Autor (Nombre) VALUES ('Michael Jordan'); 
INSERT INTO Autor (Nombre) VALUES ('Rick Steves'); 
INSERT INTO Autor (Nombre) VALUES ('Paul Krugman'); 

--libros de los autores y editoriales

INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES ('Harry Potter y la Piedra Filosofal', 5, 4);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES ('Harry Potter y la Cámara Secreta', 5, 4);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES ('Harry Potter y el Prisionero de Azkaban', 5, 4);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('1984', 6, 3);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Rebelión en la Granja', 6, 3);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Homenaje a Cataluña', 3, 3);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Resplandor', 7, 6);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Cementerio de Animales', 7, 6);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('It', 7, 6);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Narraciones Extraordinarias', 7, 7);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Cuervo y Otros Poemas', 7, 7);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Los Crímenes de la Calle Morgue', 7, 7);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Fundación', 6, 8);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Yo, Robot', 6, 8);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Los Propios Dioses', 6, 8);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Hobbit', 5, 9);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('La Comunidad del Anillo', 5, 9);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Las Dos Torres', 5, 9);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Los Juegos del Hambre', 6, 10);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('En Llamas', 6, 10);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Sinsajo', 6, 10);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Estructuras Sintácticas', 1, 11);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Conocimiento del Lenguaje', 1, 11);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Manufacturing Consent', 3, 11);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Cien Años de Soledad', 2, 12);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Amor en los Tiempos del Cólera', 2, 12);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Crónica de una Muerte Anunciada', 2, 12);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('La Llamada de Cthulhu', 7, 1);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('En las Montañas de la Locura', 7, 1);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Horror de Dunwich', 7, 1);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('¿Sueñan los androides con ovejas eléctricas?', 6, 2);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Hombre en el Castillo', 6, 2);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Ubik', 6, 2);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Camino de los Reyes', 5, 5);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Imperio Final', 5, 5);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Héroe de las Eras', 5, 5);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Diario de Frida Kahlo', 8, 13);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Frida Kahlo: Sus Fotos', 8, 13);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Retratos de Frida', 8, 13);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Fantasma de la Ópera', 9, 14);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Evita: The Real Life of Eva Perón', 9, 14);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Jesus Christ Superstar: The Complete Libretto', 9, 14);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Michael Jordan: The Life', 10, 15);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('For the Love of the Game', 10, 15);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Driven from Within', 10, 15);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Europe Through the Back Door', 11, 16);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Rick Steves Italy', 11, 16);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Rick Steves Spain', 11, 16);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('El Retorno de la Depresión Económica', 12, 17);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('La Consciencia de un Liberal', 12, 17);
INSERT INTO Libro (Titulo, ID_Categoria, ID_Editorial) VALUES 
('Economía Internacional', 12, 17);

--bibliotecarios

INSERT INTO Bibliotecario (Nombre, Email, Telefono) VALUES ('Ana Martínez', 'ana.martinez@biblioteca.com', '3001234567');
INSERT INTO Bibliotecario (Nombre, Email, Telefono) VALUES ('Carlos Gómez', 'carlos.gomez@biblioteca.com', '3109876543');

--orden ejemplares

INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (1, 1, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (2, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (3, 1, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (7, 1, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (10, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (1, 1, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (2, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (3, 1, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (5, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (6, 1, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (7, 1, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (8, 2, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (10, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (11, 1, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (13, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (14, 1, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (16, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (17, 1, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (19, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (20, 1, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (22, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (23, 1, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (25, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (26, 1, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (28, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (29, 1, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (31, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (32, 1, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (34, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (35, 1, 2);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (37, 2, 1);
INSERT INTO Ejemplar (ID_Libro, ESTADO_ID, ID_Sucursal) VALUES (38, 1, 2);

--estado de los pedidos

INSERT INTO Estado_Pedido (Estado) VALUES ('En Proceso');
INSERT INTO Estado_Pedido (Estado) VALUES ('Completado');
INSERT INTO Estado_Pedido (Estado) VALUES ('Cancelado');
INSERT INTO Estado_Multa (Estado) VALUES ('Pendiente');
INSERT INTO Estado_Multa (Estado) VALUES ('Pagada');


INSERT INTO Usuario (Nombre, Direccion, Telefono, Email, Fecha_Registro)
VALUES ('Juan Pérez', 'Calle 12-23', '3124567890', 'juan.perez@example.com', TO_DATE('2025-01-15', 'YYYY-MM-DD'));

--usuarios y prestamos

INSERT INTO Prestamo (ID_Usuario, ID_Ejemplar, ID_Bibliotecario, Fecha_Alquiler, Fecha_Devolucion, Devuelto)
VALUES (1, 1, 1, TO_DATE('2025-03-01', 'YYYY-MM-DD'), TO_DATE('2025-03-15', 'YYYY-MM-DD'), 'Y');

INSERT INTO Prestamo (ID_Usuario, ID_Ejemplar, ID_Bibliotecario, Fecha_Alquiler, Fecha_Devolucion, Devuelto)
VALUES (1, 1, 1, TO_DATE('2025-03-01', 'YYYY-MM-DD'), TO_DATE('2025-03-15', 'YYYY-MM-DD'), 'Y');

INSERT INTO Prestamo (ID_Usuario, ID_Ejemplar, ID_Bibliotecario, Fecha_Alquiler, Fecha_Devolucion, Devuelto)
VALUES (2, 2, 2, TO_DATE('2025-03-05', 'YYYY-MM-DD'), TO_DATE('2025-03-20', 'YYYY-MM-DD'), 'N');

INSERT INTO Prestamo (ID_Usuario, ID_Ejemplar, ID_Bibliotecario, Fecha_Alquiler, Fecha_Devolucion, Devuelto)
VALUES (3, 3, 1, TO_DATE('2025-02-25', 'YYYY-MM-DD'), TO_DATE('2025-03-10', 'YYYY-MM-DD'), 'Y');

INSERT INTO Prestamo (ID_Usuario, ID_Ejemplar, ID_Bibliotecario, Fecha_Alquiler, Fecha_Devolucion, Devuelto)
VALUES (5, 6, 2, TO_DATE('2025-03-12', 'YYYY-MM-DD'), TO_DATE('2025-03-27', 'YYYY-MM-DD'), 'Y');

INSERT INTO Prestamo (ID_Usuario, ID_Ejemplar, ID_Bibliotecario, Fecha_Alquiler, Fecha_Devolucion, Devuelto)
VALUES (9, 11, 1, TO_DATE('2025-03-01', 'YYYY-MM-DD'), TO_DATE('2025-03-16', 'YYYY-MM-DD'), 'Y');

INSERT INTO Prestamo (ID_Usuario, ID_Ejemplar, ID_Bibliotecario, Fecha_Alquiler, Fecha_Devolucion, Devuelto)
VALUES (1, 2, 1, TO_DATE('2025-03-05', 'YYYY-MM-DD'), TO_DATE('2025-03-20', 'YYYY-MM-DD'), 'N');

INSERT INTO Prestamo (ID_Usuario, ID_Ejemplar, ID_Bibliotecario, Fecha_Alquiler, Fecha_Devolucion, Devuelto)
VALUES (2, 3, 2, TO_DATE('2025-03-07', 'YYYY-MM-DD'), TO_DATE('2025-03-22', 'YYYY-MM-DD'), 'Y');

INSERT INTO Prestamo (ID_Usuario, ID_Ejemplar, ID_Bibliotecario, Fecha_Alquiler, Fecha_Devolucion, Devuelto)
VALUES (4, 5, 1, TO_DATE('2025-03-11', 'YYYY-MM-DD'), TO_DATE('2025-03-26', 'YYYY-MM-DD'), 'Y');

INSERT INTO Prestamo (ID_Usuario, ID_Ejemplar, ID_Bibliotecario, Fecha_Alquiler, Fecha_Devolucion, Devuelto)
VALUES (5, 6, 2, TO_DATE('2025-03-13', 'YYYY-MM-DD'), TO_DATE('2025-03-28', 'YYYY-MM-DD'), 'Y');

INSERT INTO Prestamo (ID_Usuario, ID_Ejemplar, ID_Bibliotecario, Fecha_Alquiler, Fecha_Devolucion, Devuelto)
VALUES (7, 8, 1, TO_DATE('2025-03-19', 'YYYY-MM-DD'), TO_DATE('2025-04-03', 'YYYY-MM-DD'), 'Y');

--creacion de indices

CREATE INDEX idx_estado_ejemplar_estado ON Estado_Ejemplar (Estado);
CREATE INDEX idx_estado_multa_estado ON Estado_Multa (Estado);
CREATE INDEX idx_estado_pedido_estado ON Estado_Pedido (Estado);
CREATE INDEX idx_usuario_nombre ON Usuario (Nombre);
CREATE INDEX idx_categoria_nombre ON Categoria (Nombre_Categoria);
CREATE INDEX idx_editorial_nombre ON Editorial (Nombre);
CREATE INDEX idx_sucursal_nombre ON Sucursal (Nombre_Sucursal);
CREATE INDEX idx_libro_categoria_editorial ON Libro (ID_Categoria, ID_Editorial);
CREATE INDEX idx_ejemplar_estado_sucursal ON Ejemplar (Estado_ID, ID_Sucursal);
CREATE INDEX idx_prestamo_usuario ON Prestamo (ID_Usuario);
CREATE INDEX idx_prestamo_bibliotecario ON Prestamo (ID_Bibliotecario);
CREATE INDEX idx_historial_prestamo ON Historial_Prestamos (ID_Prestamo);
CREATE INDEX idx_multa_usuario_prestamo ON Multa (ID_Usuario, ID_Prestamo);
CREATE INDEX idx_pedido_usuario_estado ON Pedido (ID_Usuario, Estado_ID);
CREATE INDEX idx_autor_nombre ON Autor (Nombre);

--creacion de vistas

CREATE VIEW Vista_Libros AS
SELECT 
    L.ID_Libro,
    L.Titulo,
    C.Nombre_Categoria AS Categoria,
    E.Nombre AS Editorial
FROM 
    Libro L
JOIN 
    Categoria C ON L.ID_Categoria = C.ID_Categoria
JOIN 
    Editorial E ON L.ID_Editorial = E.ID_Editorial;

CREATE VIEW Vista_Ejemplares AS
SELECT 
    E.ID_Ejemplar,
    L.Titulo,
    SE.Estado AS Estado_Ejemplar,
    S.Nombre_Sucursal AS Sucursal
FROM 
    Ejemplar E
JOIN 
    Libro L ON E.ID_Libro = L.ID_Libro
JOIN 
    Estado_Ejemplar SE ON E.Estado_ID = SE.ID_Estado
JOIN 
    Sucursal S ON E.ID_Sucursal = S.ID_Sucursal;

CREATE VIEW Vista_Usuarios_Prestamos AS
SELECT 
    U.Nombre AS Usuario,
    P.Fecha_Alquiler,
    P.Fecha_Devolucion,
    P.Devuelto
FROM 
    Usuario U
JOIN 
    Prestamo P ON U.ID_Usuario = P.ID_Usuario;


CREATE VIEW Vista_Multas AS
SELECT 
    M.ID_Multa,
    U.Nombre AS Usuario,
    M.Monto,
    SM.Estado AS Estado_Multa
FROM 
    Multa M
JOIN 
    Usuario U ON M.ID_Usuario = U.ID_Usuario
JOIN 
    Estado_Multa SM ON M.Estado_ID = SM.ID_Estado;


CREATE VIEW Vista_Pedidos_Pagos AS
SELECT 
    P.ID_Pedido,
    U.Nombre AS Usuario,
    P.Fecha_Pedido,
    P.Total,
    SP.Estado AS Estado_Pedido,
    PA.Monto AS Monto_Pago,
    PA.Fecha_Pago,
    PA.Metodo_Pago
FROM 
    Pedido P
JOIN 
    Usuario U ON P.ID_Usuario = U.ID_Usuario
JOIN 
    Estado_Pedido SP ON P.Estado_ID = SP.ID_Estado
LEFT JOIN 
    Pago PA ON P.ID_Pedido = PA.ID_Pedido;


CREATE VIEW Vista_Historial_Prestamos AS
SELECT 
    HP.ID_Historial,
    P.ID_Prestamo,
    HP.Estado AS Estado_Prestamo,
    HP.Fecha_Cambio
FROM 
    Historial_Prestamos HP
JOIN 
    Prestamo P ON HP.ID_Prestamo = P.ID_Prestamo;


--consultas

SELECT * FROM Libro;

SELECT * FROM Ejemplar WHERE ID_Libro = 1;

SELECT * FROM Usuario;

SELECT SE.Estado FROM Estado_Ejemplar SE
JOIN Ejemplar E ON SE.ID_Estado = E.Estado_ID
WHERE E.ID_Ejemplar = 1;

SELECT L.Titulo, C.Nombre_Categoria
FROM Libro L
JOIN Categoria C ON L.ID_Categoria = C.ID_Categoria
WHERE C.Nombre_Categoria = 'Ciencia Ficción';

SELECT * FROM Prestamo WHERE ID_Usuario = 1;

SELECT 
    L.Titulo, 
    SE.Estado AS Estado_Ejemplar, 
    S.Nombre_Sucursal
FROM 
    Ejemplar E
JOIN 
    Libro L ON E.ID_Libro = L.ID_Libro
JOIN 
    Estado_Ejemplar SE ON E.Estado_ID = SE.ID_Estado
JOIN 
    Sucursal S ON E.ID_Sucursal = S.ID_Sucursal;
    
SELECT 
    L.Titulo, 
    COUNT(P.ID_Prestamo) AS Veces_Prestado
FROM 
    Prestamo P
JOIN 
    Ejemplar E ON P.ID_Ejemplar = E.ID_Ejemplar
JOIN 
    Libro L ON E.ID_Libro = L.ID_Libro
GROUP BY 
    L.Titulo
ORDER BY 
    Veces_Prestado DESC;


SELECT 
    U.Nombre AS Usuario, 
    COUNT(P.ID_Prestamo) AS Total_Prestamos
FROM 
    Usuario U
JOIN 
    Prestamo P ON U.ID_Usuario = P.ID_Usuario
GROUP BY 
    U.Nombre;



SELECT 
    L.Titulo, 
    SE.Estado AS Estado_Ejemplar, 
    S.Nombre_Sucursal
FROM 
    Libro L
JOIN 
    Ejemplar E ON L.ID_Libro = E.ID_Libro
JOIN 
    Estado_Ejemplar SE ON E.Estado_ID = SE.ID_Estado
JOIN 
    Sucursal S ON E.ID_Sucursal = S.ID_Sucursal
WHERE 
    L.ID_Libro = 1;


SELECT 
    L.ID_Libro, 
    L.Titulo, 
    C.Nombre_Categoria, 
    E.Nombre AS Editorial,
    S.Nombre_Sucursal, 
    COUNT(Ej.ID_Ejemplar) AS Ejemplares_Disponibles
FROM 
    Libro L
JOIN 
    Categoria C ON L.ID_Categoria = C.ID_Categoria
JOIN 
    Editorial E ON L.ID_Editorial = E.ID_Editorial
JOIN 
    Ejemplar Ej ON L.ID_Libro = Ej.ID_Libro
JOIN 
    Sucursal S ON Ej.ID_Sucursal = S.ID_Sucursal
GROUP BY 
    L.ID_Libro, L.Titulo, C.Nombre_Categoria, E.Nombre, S.Nombre_Sucursal
ORDER BY 
    L.Titulo;



SELECT 
    P.ID_Prestamo, 
    U.Nombre AS Usuario, 
    E.ID_Ejemplar, 
    B.Nombre AS Bibliotecario, 
    P.Fecha_Alquiler, 
    P.Fecha_Devolucion, 
    P.Devuelto
FROM 
    Prestamo P
JOIN 
    Usuario U ON P.ID_Usuario = U.ID_Usuario
JOIN 
    Ejemplar E ON P.ID_Ejemplar = E.ID_Ejemplar
JOIN 
    Bibliotecario B ON P.ID_Bibliotecario = B.ID_Bibliotecario
ORDER BY 
    P.Fecha_Alquiler DESC;


